#!/bin/bash
if [[ "$2" = "t" ]]; then 
	ls "$1.tex" "$1.bbl" | entr pdflatex -interaction=nonstopmode -file-line-error "$1.tex" | grep "\./" & ls "$1.pdf" | entr pkill -HUP mupdf
elif [[ "$2" = "m" ]]; then
	ls "$1.md" | entr pandoc -t latex "$1.md" -o "$1.pdf" & ls "$1.pdf" | entr pkill -HUP mupdf
fi
