#!/bin/bash
export DBUS_SESSION_BUS_ADDRESS=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/$(pidof i3)/environ | cut -d= -f2-)

BATTERY_LEVEL=$(cat /sys/class/power_supply/BAT1/capacity)
BATTERY_STATUS=$(cat /sys/class/power_supply/BAT1/status)
if [[ $BATTERY_LEVEL -lt 10 ]] && [[ $BATTERY_STATUS != "Charging" ]]; then
	notify-send --urgency=critical "BATTERY CRITICAL: $BATTERY_LEVEL %"
fi
