#!/bin/bash
DIRECTORY_CONTENTS=(*)
COUNTER=0
touch /tmp/rename
for name in "${DIRECTORY_CONTENTS[@]}"; do
	echo $name >> /tmp/rename
done
$EDITOR /tmp/rename && 
for name in $(cat /tmp/rename); do
	$(mv -n "${DIRECTORY_CONTENTS[$COUNTER]}" "$name" 2> /dev/null)
	COUNTER=$((COUNTER + 1))
done
rm /tmp/rename
