#!/bin/bash
watch_folder=~/.rtorrent/watch
cd $watch_folder
[[ "$1" =~ xt=urn:btih:([^&/]+) ]] || exit;
TIME=$(date +%s%N)
echo "d10:magnet-uri${#1}:${1}e" > "$TIME.torrent" && st -e rtorrent "$TIME.torrent"

